# Generated by Django 2.0 on 2020-01-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latestnews',
            options={'verbose_name_plural': 'Latest News'},
        ),
    ]
