# Generated by Django 2.0 on 2020-01-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlist',
            name='location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
