# Generated by Django 2.0 on 2020-01-10 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0002_auto_20200110_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientlist',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
