# Generated by Django 2.0 on 2020-01-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0003_auto_20200110_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientListOutside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Client List North East and beyond',
            },
        ),
        migrations.RenameModel(
            old_name='ClientList',
            new_name='ClientListKamrup',
        ),
        migrations.AlterModelOptions(
            name='clientlistkamrup',
            options={'verbose_name_plural': 'Client List Locations in Kamrup'},
        ),
    ]
