# Generated by Django 2.0 on 2020-01-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='user_type',
            field=models.CharField(default='Client', max_length=50),
        ),
    ]
