# Generated by Django 2.0 on 2020-01-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerquery',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='careerquery',
            name='files',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='careerquery',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
