# Generated by Django 2.2 on 2020-04-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0003_auto_20200110_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
