# Generated by Django 2.2 on 2020-02-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_opening',
            name='job_type',
            field=models.CharField(blank=True, default='Sss', help_text='Full Time / Part Time', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_opening',
            name='location',
            field=models.CharField(blank=True, default='guwahati', max_length=100),
            preserve_default=False,
        ),
    ]
