# Generated by Django 2.2 on 2020-04-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20200219_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_opening',
            name='experience',
            field=models.CharField(blank=True, help_text='Experience', max_length=100),
        ),
    ]
