# Generated by Django 2.2 on 2020-04-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_job_opening_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_opening',
            name='salary_range',
            field=models.CharField(blank=True, help_text='1.5 - 2.5 Lac', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_opening',
            name='title',
            field=models.CharField(blank=True, help_text='Optional', max_length=100, null=True),
        ),
    ]
