# Generated by Django 2.2 on 2020-04-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_auto_20200402_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_opening',
            name='open_positions',
            field=models.CharField(blank=True, help_text='Number of Empty Positions', max_length=100),
        ),
    ]
